LD4RAIL migration ontology 3.1.0 (11-11-2024)
Interoperable-data/ERA-Ontology-3.1.0 pull request #127
Opened 2024-11-13 18:23 UTC by ednaru

- Delete property hasSetParameters (duplicate with belongTo)
- Add inverse axiom to property contains: inverse of belomgsTo
- Added domain to 1.1.1.3.8.1.1. Track or CommonCharacteristicsSubset
- Added CommonCharacteristics subset to domain of Platform, Siding, OperationalPoint and Tunnel parameters
- Removed CommonCharacteristicsSubset from domain of ContactLineSystem, Train DetectionSystem and ETCS
- Removed annotation RINF index from those RINF parameters that have been deprecated but that are maintained because there also ERATV and removed Track, CommonCharacteristicsSubset from Domain
- Remove deprecated axiom from trainDetectionSystemSpecificCheck, 1.1.1.3.8.2
- Added transitive axiom to subsetOf property between two CommonCharacteristicsSubset
- Changed property 1.1.1.1.7.3 accelerationLevelCrossing to an object property with range Document
- Changed property nationalRailwayIdentification to an object property that points to NationalRailwayLine

2024-11-14 07:10 UTC, gatemezing requested changes
Please review the output for the ontology metadata generated by Protégé to align with the current one. Additionally, please find an URI for UPM.

2024-11-14 07:10 UTC, gatemezing commented on ontology.ttl
Do you have a URI for UPM as we have for ERA?

2024-11-14 07:10 UTC, gatemezing commented on ontology.ttl
We need to manually check this output for metadata from Protégé

2024-11-14 07:40 UTC, ednaru commented on ontology.ttl
Added URI for UPM. Lines 28-33

2024-11-14 07:42 UTC, ednaru commented on ontology.ttl
I left the metadata for contributors, lines 22-45 and deleted the extra triples for person(s) that were at the end of the file

2024-11-17 10:33 UTC, gatemezing commented
Check and fix also these three `era:rinfIndex` with language tags: 

-  "1.1.1.1.8"@en 
- "1.1.1.3.10"@en
-  "1.1.1.3.9"@en

2024-11-17 17:47 UTC, closed without merging

2024-11-17 17:48 UTC, ednaru commented
This branch has an ontology.ttl file that is corrupted due to some issue with the Protégé tool. Will redo this updates in a new branch