updated skos values & added altLabel tag for CCSTMS
Interoperable-data/ERA-Ontology-3.1.0 pull request #149
Opened 2024-12-11 22:32 UTC by Ajala111

[AtoGradesAutomation, LoadCapabilityLineCategories, PlatformHeight, NominalTrackGauge, OperationalPointType, ETCSMVersion, ETCSLevel, EnergySupplySystem, CantDeficiencies, ETCSReactionNVContact, TrainDetectionSystem, TransmittedTrackConditions, TrackRunningDirection ]

AtoGradesAutomation
	- GoA3 , GoA4, GoAUnknown <-- added
CantDeficiencies:
	- Undefined <-- missing (added)
LoadCapabilityLineCategories
	- HS17 <-- missing (added)
NominalTrackGauge:
	- Unknown <-- missing added)
EnergySupplySystem:
	- NotFitted <-- missing (added)
TransmittedTrackConditions
	- bigMetalMasses, switchOffRegenerativeBrake, switchOffEddyCurrentBrakeForServiceBrake, switchOffEddyCurrentBrakeForEmergencyBrake, switchOffMagneticShoeBrake

2024-12-11 22:57 UTC, gatemezing reviewed
Asking for small clarifications - thanks for the input

2024-12-11 22:57 UTC, gatemezing commented on era-skos/era-skos-ATOGradesAutomation.ttl
What means an unknown category in your use case? Could we avoid having such type? Or there is a clear need of saying we don’t know in OWA ?

2024-12-12 09:11 UTC, Ajala111 commented on era-skos/era-skos-ATOGradesAutomation.ttl
Yes, the unknown category is needed where they're included; sometimes situations are encountered  where, for example, grade of automation (GoA) for a segment/SoL is genuinely unknown (e.g., during maintenance, system testing, or engineering ). It prevents the application from failing or requiring a value when the actual level cannot yet be determined.

2024-12-12 16:01 UTC, gatemezing requested changes
As discussed in the latest comment, let's agree the following:

-  No need to have unknown URIs ?
- change skos:altLabel to skos:hiddenLabel

2024-12-12 16:01 UTC, gatemezing commented on era-skos/era-skos-NominalTrackGauges.ttl
> +  skos:altLabel "CCSTMS_tg1520mm_4" ;
Dear @Ajala111, based on today's discussion, could you change `skos:altLabel `to `skos:hiddenLabel` ?

2024-12-12 17:56 UTC, Ajala111 commented on era-skos/era-skos-NominalTrackGauges.ttl
> +  skos:altLabel "CCSTMS_tg1520mm_4" ;
The use of 'unknown' is necessary and goes beyond merely replacing it with optionality for the attribute. 
These attributes using them are required, and having 'unknown' explicitly as a value serves as a clear statement of fact. This clarity can guide further decision-making processes.

Using values like Unknown, None, or similar indicators is a widely accepted practice, particularly when required for completeness. RSM, EULYNX, etc also employed this approach.

@gatemezing thanks. I'll update the altLabel as discussed.

2024-12-12 19:42 UTC, gatemezing reviewed
please review my last comments. thank you!

2024-12-12 19:42 UTC, gatemezing commented on era-skos/era-skos-TransmittedTrackConditions.ttl
>    rdfs:comment "Big metal masses, ignore on-board integrity check alarm of balise transmission" ;
Todo: change` rdfs:comment` to `skos:definition `for consistency with language tag. 

Instead of 
`rdfs:comment "Big metal masses, ignore on-board integrity check alarm of balise transmission" ` use 

`skos:definition "Big metal masses, ignore on-board integrity check alarm of balise transmission" @en `

2024-12-12 19:42 UTC, gatemezing commented on era-skos/era-skos-TransmittedTrackConditions.ttl
>    rdfs:comment "defines a switch Off Regenerative Brake sections" ;
Same comment as above

2024-12-12 19:42 UTC, gatemezing commented on era-skos/era-skos-TransmittedTrackConditions.ttl
>    rdfs:comment "defines a switch Off Eddy Current Brake sections" ;
same comment as above

2024-12-12 19:42 UTC, gatemezing commented on era-skos/era-skos-TransmittedTrackConditions.ttl
>    skos:prefLabel "switchOffRegenerativeBrake"@en .
For skos:prefLabel, try to use a human readable name. Instead of 
`skos:prefLabel "switchOffRegenerativeBrake"@en ` , use 

`skos:prefLabel "switch Off Regenerative Brake"@en" `  and keep the skos:hiddenLabel as it is.

2024-12-16 08:55 UTC, gatemezing reviewed
Missing some skos:notation in the new concepts added in this PR.
Basically, if in the Turtle file, there is a use of the property `skos:notation`, be consistent in the updates for the file. Of course, if there is no use of skos:notation, do not add the property to be also consistent with the file. cc / @Ajala111

2024-12-16 08:55 UTC, gatemezing commented on era-skos/era-skos-ATOGradesAutomation.ttl
> +  skos:topConceptOf era-ato-grades:ATOGradeOfAutomation ;
missing skos:notation "3"^^xsd:string

2024-12-16 08:55 UTC, gatemezing commented on era-skos/era-skos-ATOGradesAutomation.ttl
> +
Add skos:notation for "4" and "unknown"

2024-12-16 08:55 UTC, gatemezing commented on era-skos/era-skos-NominalTrackGauges.ttl
> +  skos:definition "Track gauge type not known"@en ;
add skos:notation "unknown"^^xsd:string

2024-12-16 08:55 UTC, gatemezing commented on era-skos/era-skos-TransmittedTrackConditions.ttl
> +  skos:definition "Big metal masses, ignore on-board integrity check alarm of balise transmission"@en ;
add skos:notation for the new concepts

2024-12-17 07:57 UTC, gatemezing approved these changes
good, time to merge!

2024-12-17 07:57 UTC, merged