Updates in line with Technical Annex (CCS parameters)
Interoperable-data/ERA-Ontology-3.1.0 pull request #31
Opened 2024-06-03 17:17 UTC by Certiman

Please note I also used:
- `dcterms:source` for the "Reference", i.e the EULEX or ERA document describing the basis of the parameter
- `rdfs:requires` for the "Applicable" - conditions
- `dcterms:relation` to link to another parameter if there is a dependency
- `dcterms:description` for the "Explanations" or any data not in Defintion/Data presentation.

The `dcterms`-prefix was therefore also added.

2024-06-04 07:37 UTC, gatemezing requested changes
See the comments in the reviw

2024-06-04 07:37 UTC, gatemezing commented on ontology.ttl
> +                               dcterms:source "https://www.era.europa.eu/system/files/2023-09/index077_-_ERA_ERTMS_033281_v5.pdf" ;
dcterms:source should point to an URI, so change it to be` dcterms:source <https://www.era.europa.eu/system/files/2023-09/index077_-_ERA_ERTMS_033281_v5.pdf>`

2024-06-04 07:37 UTC, gatemezing commented on ontology.ttl
> +                                   dcterms:source "https://www.era.europa.eu/system/files/2023-09/index077_-_ERA_ERTMS_033281_v5.pdf" ;
same as above for dcterms:source

2024-06-04 07:37 UTC, gatemezing commented on ontology.ttl
> +                                   dcterms:source "https://www.era.europa.eu/system/files/2023-09/index077_-_ERA_ERTMS_033281_v5.pdf" ;
range of dcterms:source a URI

2024-06-04 07:37 UTC, gatemezing commented on ontology.ttl
> +                           dcterms:source "According to the specification referenced in Appendix A-1, index [C]"@en ;
dcterms:source should be a URI

2024-06-04 07:37 UTC, gatemezing commented on ontology.ttl
> +                 dcterms:source "TBD"@en ;
Let's avoid "TBD3 if possible

2024-06-04 07:37 UTC, gatemezing commented on ontology.ttl
> +               dcterms:source "TSI CCS 4.2.2"@en ;
dcterms;source should be a URI

2024-06-04 07:37 UTC, gatemezing commented on ontology.ttl
> +                 dcterms:source "According to the specification referenced in Appendix A-1, index [C]"@en ;
same comment for dcterms;source range as URI

2024-06-04 07:37 UTC, gatemezing commented on ontology.ttl
> +                            dcterms:definition "TBD"@en ;
let's avoid TBD

2024-06-04 07:37 UTC, gatemezing commented on ontology.ttl
> +	         rdfs:seeAlso "http://data.europa.eu/eli/dir/2012/34/oj (Article 3(2))." ;
s/rdfs:seeAlso "http://data.europa.eu/eli/dir/2012/34/oj (Article 3(2))."/` rdfs:seeAlso <http://data.europa.eu/eli/dir/2012/34/oj (Article 3(2))>`

2024-06-04 10:28 UTC, Certiman commented
@gatemezing , thanks for a second review.

2024-06-05 10:21 UTC, gatemezing approved these changes
Good to go :)

2024-06-05 10:21 UTC, merged